config/routes.rb
Rails.application.routes.draw do


  root 'application#index'
  
  get '/login' => 'sessions#new', as: :login
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy', as: :logout

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  # allows this to be referred to as profile path in views
  get 'profile/:id', to: 'profiles#show', as: 'profile'

  resources :users
  resources :profiles
  resources :friendships
  resources :account_activations, only: [:edit]
  resources :notifications, only: [:create, :destroy]
  resources :messages
  get '/deletemsg' => 'messages#destroy', as: :msgdelete

end

app/models/notification.rb
class Notification < ActiveRecord::Base

  #belongs_to :document
  #accepts_nested_attributes_for :document
  # mount_uploader :picture, PictureUploader

  belongs_to :user
  default_scope -> { order(created_at: :desc) } # ensures that most recent notification is first 
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
  validate :picture_size # custom validation so use validate instead of validation
  field :body

  private

#     # Validates size of uploaded picture
#     def picture_size
#       if picture.size > 5.megabytes
#         errors.add(:picture, "should be less than 5MB")
#       end
#     end
# end

app/controllers/notifications_controller.rb
# class NotificationsController < ApplicationController

#   before_action :logged_in_user, only: [:create, :destroy]
#   before_action :correct_user, only: :destroy

#   def index
#     @notifications = current_user.notifications

#   def new
#     @notification = Notification.new

#   def create
#     @notification = Notification.new(params.require(:notification).permit(:body))
#     if @notification.save
#       flash[:success] = "A new notification has been created"
#     else
#       render :new
#     end
#   end

#   def destroy
#     @notification.destroy
#     flash[:success] = "Notification deleted"
#     redirect_to request.referrer || root_url
#     # request.referrer redirects back to page giving delete request both cases
#   end

#   private

#     def notification_params
#       params.require(:notification).permit(:content, :picture)
#     end

#     def correct_user
#       @notification = current_user.notifications.find_by(id: params[:id])
#       redirect_to root_url if @notification.nil?
#     end
# end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_notification.html.erb
<!-- <li id="notification-<%= notification.id %>">
  <span class="user"><%= link_to notification.user.full_name, notification.user %></span>
  <span class="content">
    <%= notification.content %>
    <%= image_tag notification.picture_url if notification.picture? %> 

  </span>

  <span class="timestamp">
    Posted <%= time_ago_in_words(notification.created_at) %> ago.
    <% if current_user?(notification.user) %> 
      <%= link_to "delete", notification, method: :delete,
                                          data: { confirm: "Are you sure?" } %>
    <% end %>
  </span>
</li> -->

app/views/notifications/index.html.erb
<%= link_to "Relocating or taking a trip? Let your friends know!", new_notification_path, class: "btn btn-success" %>
<%= @notifications.each do |notification| %>
<div class="notification">
  <div class="row">
    <div class="span1">
      <%= link_to image_tag(status.user.gravatar_url), profile_path(notification.user) %>
    </div>
    <div class="span7">
      <%= notification.user.full_name %>
      <p><%= notification.content %></p>
      <div class="meta">
        <%= link_to time_ago_in_words(notification.created_at) + " ago", notification %>
        <span class="admin">
          | <%= link_to "Edit", edit_notification_path(notification) %> | 
          <%= link_to "Delete", notification, method: :delete, data: { confirm: "Are you sure you want to delete this notification?"} %>
        </span>
      </div>
    </div>
  </div>
</div>
<% end %>