config/routes.rb
Rails.application.routes.draw do


  root 'application#index'
  
  get '/login' => 'sessions#new', as: :login
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy', as: :logout

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  # allows this to be referred to as profile path in views
  get 'profile/:id', to: 'profiles#show', as: 'profile'

  resources :users
  resources :profiles
  resources :friendships
  resources :account_activations, only: [:edit]
  resources :notifications, only: [:create, :destroy]
  resources :messages
  get '/deletemsg' => 'messages#destroy', as: :msgdelete

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

  def index 
  end

  #  # Confirms that user is logged in. 
  # def logged_in_user
  #   unless logged_in?
  #      redirect_to login_url
  #   end
  # end

  # def logged_in? 
  #   current_user
  # end
  #   helper_method :logged_in?

  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    elsif cookies.permanent.signed[:remember_me_token]
      verification = Rails.application.message_verifier(:remember_me).verify(cookies.permanent.signed[:remember_me_token])
      if verification
        Rails.logger.info "Logging in through cookie"
        @current_user ||= User.find(verification)
      end
    end
  end
  helper_method :current_user

  def require_user
    if current_user
      true
    else
      redirect_to new_user_session_path, notice: "You must be logged in to access this page."
    end
  end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_form.html.erb
<% form_for @invitation do |f| %>
  <p>
    <%= f.label :recipient_email, "Friends' email addresses" %><br>
    <%= f.text_field :recipient_email %><br>
  </p>
  <p><%= f.submit "Invite" %></p>
<% end %>

app/views/application/index.html.erb
<!-- Fixed navbar -->
<div class="background_image">
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="landing-page container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="navbar-collapse">
        <span class="sr-only">Toggle navigation</span> <!-- sr hides information used for screen readers -->
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="small-logo-container">
        <a class="small-logo" href="#">Six Degrees</a>
      </div>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          Signed in as <%= current_user.name %> | <li><%= link_to "LOG OUT", logout_path %></li>
        <% else %>
          <li><%= link_to 'SIGN UP', signup_path %></li>
          <li><%= link_to 'LOG IN', login_path %></li>
        <% end %>         
      </ul>
    </div>
  </div>
</div> 

<div class="container-fluid big-logo-row">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 big-logo-container">
        <h1 class="big-logo">Six Degrees</h1>
      </div>
    </div>
  </div>
</div>

<div class="log-in container">
  <div class="row">
    <div class="col-lg-5 col-md-6 col-sm-8">
      <% if current_user %>
      <%= current_user.username %>
      <% end %>
      <h2>ABOUT</h2>
        <p class="about">

        We are often asked how the idea for our company first started. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
        <br>
        Ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
        <br>
        Ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
      </p>
    </div>
  </div>
</div>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<div id="myCarousel">
  <div id="landing-page-carousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#carousel-example-first" data-slide-to="0" class="active"></li>
      <li data-target="#carousel-example-second" data-slide-to="1" class="active"></li>
      <li data-target="#carousel-example-third" data-slide-to="2" class="active"></li>
    </ol>
   
    <!-- Wrapper for slides -->
    <div class="carousel-inner">
      <div class="item active">
        <img src="http://feejeeexperience.com/blog/wp-content/uploads/2014/07/FeeJee-Backpacking-in-Fiji-140728.jpg" alt="backpackers" style="width:620px; height:360px" >
        <div class="carousel-caption">
            <h3>Find someone to travel with...</h3>
        </div>
      </div>
      <div class="item">
        <img src="http://www.athomeinlove.com/wp-content/uploads/2013/04/dining-alfreco.jpg" alt="alfresco"  style="width:620px; height:360px" >
        <div class="carousel-caption">
            <h3>and dine with...</h3>
        </div>
      </div>
      <div class="item">
        <img src="http://www.turnbacktogod.com/wp-content/uploads/2009/03/friendships-road.jpg" alt="friendship" style="width:620px; height:360px" >
        <div class="carousel-caption">
            <h3>through Six Degrees</h3>
        </div>
      </div>
    </div>
   
    <!-- Controls -->
    <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left"></span>
    </a>
    <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right"></span>
    </a>
  </div>
</div> <!-- Carousel -->
<script>
    $('.carousel').carousel({
        interval: 3000
    })
</script>
</div> 